version: '2.2'
services:
    backend:
        container_name: backend
        build: .
        image: backend
        volumes:
            - /home/athipat/Backend/public:/tmp
        restart: always
        
networks:
        default:
            external:
                name: project221

