version: '2.2'
services:
    backend:
        container_name: backend
        build: .
        image: backend
        volumes:
            - /home/athipat/Backend/public:/tmp
        environment:
            - MYSQL_DATABASE=smartphonedb
            - MYSQL_USER=user132
            - MYSQL_ROOT_PASSWORD=warm12344
        ports:
            - "3000:3000"
        restart: always
        
networks:
        default:
            external:
                name: project221

