version: '2.2'
services:
    backend:
        container_name: backend
        build: .
        image: backend
        volumes:
            - :/tmp
        ports:
            - "3000:3000"
        restart: always
networks:
        default:
            external:
                name: int221-project

